# .pre-commit-config.yaml
repos:
  - repo: local
    hooks:
    
      - id: strip-exif
        name: Strip EXIF metadata from images
        entry: bash scripts/check-exif.sh --strip
        language: system
        types: [image]
        files: \.(jpg|jpeg|png)$