baseURL: "/"
languageCode: "en-us"
title: "HUGO IMAGES IS HARD"
theme: "PaperMod"
relativeURLs: true
canonifyURLs: false

params:
  optimizeImages: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowShareButtons: true
  defaultTheme: auto
  displayFullLangName: true
  description: "WHY IS IMAGES HARD"
  mainSections: ["posts", "about"]
  showFeaturedPost: true

menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 2

    - identifier: about
      name: About
      url: /about/
      weight: 1

markup:
  goldmark:
    renderer:
      unsafe: true

module:
  mounts:
    - source: assets
      target: assets
    - source: static
      target: assets