baseURL: "/"
languageCode: "en-us"
title: "6307635 - Sea Blue & Sketchy 🌊🔌"
theme: "PaperMod"
relativeURLs: true
canonifyURLs: false

params:
  optimizeImages: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowShareButtons: true
  defaultTheme: auto
  displayFullLangName: true
  description: "Period-correct paint. Period-incorrect everything else."
  mainSections: ["logs", "about"]
  showFeaturedPost: true

menu:
  main:
    - identifier: logs
      name: Logs
      url: /logs/
      weight: 2

    - identifier: about
      name: About
      url: /about/
      weight: 1

markup:
  goldmark:
    renderer:
      unsafe: true

module:
  mounts:
    - source: assets
      target: assets
    - source: static
      target: assets