name: Deploy Develop Preview

on:
  push:
    branches:
      - develop
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Show Git commit info
        run: |
          echo "Commit SHA: ${{ github.sha }}"
          git log -1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.147.1"
          extended: true

      - name: Show Hugo version and environment
        run: |
          hugo version
          echo "Environment variables:"
          env | sort

      - name: Check Hugo config presence
        run: |
          echo "Looking for config.{toml,yaml,json}:"
          ls -l config.* || echo "No config file found"
          echo "Preview of config:"
          head -n 20 config.* || echo "No readable config"

      - name: Debug available themes
        run: |
          echo "Listing contents of themes directory:"
          ls -lah themes || echo "themes directory not found"
          echo "Full theme file structure:"
          find themes || echo "nothing found under themes"

      - name: Debug Hugo Modules
        run: |
          echo "Running hugo mod graph (if using modules)..."
          hugo mod graph || echo "Not using Hugo Modules or command failed"

      - name: Check theme folder mounts
        run: |
          echo "Checking mounted theme folder (themes/PaperMod)..."
          ls -lah themes/PaperMod || echo "themes/PaperMod not found"

      - name: Install exiftool
        run: sudo apt-get update && sudo apt-get install -y libimage-exiftool-perl

      - name: Run EXIF metadata check
        run: |
          bash scripts/check-exif.sh --strip
          if [ $? -ne 0 ]; then
            echo "EXIF metadata was found and has been stripped."
          fi

      - name: Build Hugo site with baseURL "/develop/"
        run: hugo --baseURL="/develop/" --destination=public/develop --minify

      - name: Debug public directory contents
        run: |
          echo "Checking if public/develop/ exists:"
          if [ -d "./public/develop" ]; then
            echo "public/develop/ directory exists"
          else
            echo "ERROR: public/develop/ directory is missing!"
            exit 1
          fi

          echo "Contents of public/develop/ directory:"
          ls -lah ./public/develop

          echo "Full file list (recursive):"
          find ./public/develop

          echo "Total files:"
          find ./public/develop -type f | wc -l

          echo "Disk usage:"
          du -sh ./public/develop

      - name: Display .gitignore (if exists)
        run: cat .gitignore || echo ".gitignore not found"

      - name: Deploy to GitHub Pages in /develop/
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public/develop
          destination_dir: develop
          force_orphan: false
          user_name: "GitHub Actions"
          user_email: "actions@github.com"
          commit_message: "Deploy from develop: ${{ github.sha }}"
